config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root to: 'homes#index'
  resources :users

  authenticate :user do
    resources :elevators, only: [:new, :create, :update, :edit] do
      resources :reviews, only: [:create]
    end
    resources :reviews, only: [:edit, :update] do
      resources :votes, only: [:create]
    end
  end

  resources :elevators, only: [:index, :show, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :reviews, only: [:destroy]

  authenticated :admin do
    resources :admins, only: [:index, :create, :destroy]
    resources :users, only: [:index, :update, :destroy]
  end
end

app/models/elevator.rb
class Elevator < ActiveRecord::Base
  mount_uploader :elevator, ElevatorUploader

  paginates_per 6
  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :building_name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :city, presence: true
  validates :zipcode, presence: true, numericality: true, length: { is: 5 }
  validates :state, presence: true
  validates :user_id, presence: true
  validates_integrity_of :elevator
  validates_processing_of :elevator

  fuzzily_searchable :building_name
  Elevator.bulk_update_fuzzy_building_name

  def average_rating
    reviews = Review.where(elevator: self)
    rtg_sum = reviews.inject(0) { |a, review| a + review.rating }
    avg = reviews.empty? ? 0 : rtg_sum.to_f / reviews.length
    avg.round
  end
end

app/controllers/elevators_controller.rb
class ElevatorsController < PermissionsController
  before_filter :require_permission, only: [:edit, :destroy]

  def index
    @elevators = Elevator.order(:building_name).page params[:page]
  end

  def show
    @elevator = Elevator.find(params[:id])
    @review = Review.new
    @rating = Review::RATING
    @reviews = @elevator.reviews.order(total_votes: :desc, created_at: :desc)
    @reviews = @reviews.page params[:page]
    @user = @elevator.user
  end

  def new
    @elevator = Elevator.new
  end

  def create
    @elevator = current_user.elevators.build(elevator_params)

    if @elevator.save
      flash[:notice] = 'You have successfully added an elevader!'
      redirect_to elevator_path(@elevator)
    else
      flash[:error] = @elevator.errors.full_messages.join('. ')
      render action: 'new'
    end
  end

  def destroy
    @elevator = Elevator.find(params[:id])
    @elevator.destroy
    flash[:notice] = "Elevator was deleted"
    redirect_to elevators_path
  end

  def edit
    @elevator = Elevator.find(params[:id])
  end

  def update
    @elevator = Elevator.find(params[:id])
    if @elevator.update(elevator_params)
      flash[:notice] = 'Elevator was updated successfully'
      redirect_to elevator_path(@elevator)
    else
      flash[:error] = @elevator.errors.full_messages.join('. ')
      render :edit
    end
  end

  def search
    @search_results = Elevator.find_by_fuzzy_building_name(params['search'])
    @ids = @search_results.map { |result| result.id }
    @elevators = Elevator.where(id: @ids)
    @elevators = @elevators.page params[:page]
    if @elevators.empty?
      flash[:alert] = "Sorry but we couldn't find that elevator for you"
    end
    render :index
  end

  private

  def elevator_params
    params.require(:elevator).permit(:building_name, :address, :city, :zipcode, :state, :elevator_cache, :elevator)
  end
end

app/views/elevators/_elevator.html.erb
<% @elevators.each do |elevator| %>
  <div class="medium-4 columns" id="elevator-<%= elevator.id %>">
    <div class="card">
      <div class="image">
        <%= link_to image_tag(elevator.elevator.medium_elevator, alt: "#{elevator.building_name}"), elevator_path(elevator) %>
      </div>
      <div class="content">
        <span> <%= "#{elevator.building_name}" %>
      </div>
    </div>
  </div>
<% end %>

app/views/elevators/_form.html.erb
<%= form_for(@elevator) do |f| %>
  <div class= "large-10 columns">
    <%= f.label :building_name %>
    <%= f.text_field :building_name %>
  </div>

  <div class= "large-10 columns">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class= "large-10 columns">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class= "large-10 columns">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  
  <div class= "large-10 columns">
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %>
  </div>

  <div class="large-10 columns">
    <%= f.label :elevator do %>
      <%= f.file_field :elevator %>
      <%= f.hidden_field :elevator_cache %>
    <% end %>
  </div>

  <div class="small-12 columns">
    <%= f.submit :class => 'button'%>
  </div>
<% end %>

app/views/elevators/_stars.html.erb
<% locals[:gold].to_i.times do %>
  <svg height="25" width="20" class="star rating" data-rating="1">
    <polygon fill="#ffbf00" points="10,0 13.09,6.583 20,7.639 15,12.764 16.18,20 10,16.583 3.82,20 5,12.764 0,7.639 6.91,6.583 "/>
  </svg>
<% end %>
<% locals[:silver].to_i.times do %>
  <svg height="25" width="20" class="star rating" data-rating="1">
    <polygon fill="#DDDDDD" points="10,0 13.09,6.583 20,7.639 15,12.764 16.18,20 10,16.583 3.82,20 5,12.764 0,7.639 6.91,6.583 "/>
  </svg>
<% end %>

app/views/elevators/edit.html.erb
<h1> Edit <%= @elevator.building_name %> </h1>
<%= render 'form' %>

app/views/elevators/index.html.erb
<div class="elevaderfont text-center"><h2></h2></div>

<div class="row">
  <% @elevators.each do |elevator| %>
      <%= link_to elevator_path(elevator) do %>
        <div class="medium-4 columns elevator-card end" id="elevator-<%= elevator.id %>">
          <div class="card elevator-card">
            <div class="image">
              <%= image_tag(elevator.elevator.medium_elevator, alt: "#{elevator.building_name}") %>
            </div>
            <div class="content text-center">
              <div> <%= "#{elevator.building_name}" %></div>
              <div class="stars">
                <%= render 'elevators/stars', locals: { gold: elevator.average_rating, silver: 5 - elevator.average_rating } %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

<%= paginate @elevators %>

<div class="row">
  <%= link_to "Add Elevator", new_elevator_path, class: "button button-span round" %>
</div>

app/views/elevators/new.html.erb
<h1>New Elevator form</h1>

<%= render 'form' %>
<%= link_to 'Back', elevators_path %>

app/views/elevators/show.html.erb
<div class="showtitle-container row">
  <div class="showtitle-item small-12">
    <div class="building-name small-10 columns">
      <h1><%= @elevator.building_name %></h1>
    </div>
    <div class="building-rating small-2 columns">
      <%= render 'elevators/stars', locals: { gold: @elevator.average_rating, silver: 5 - @elevator.average_rating } %>
    </div>
  </div>
    <% if current_user == @elevator.user || current_admin %>
      <div class="showtitle-item">
        <li> <%= link_to "Edit", edit_elevator_path(@elevator), class: "button tiny"%> </li>
      </div>
      <div class="showtitle-item">
        <li> <%= link_to "Delete", @elevator, method: :delete, data: { confirm: "Are you sure you want to delete this elevator?" }, class: "button tiny alert" %> </li>
      </div>
    <% end %>
</div>

<div class="card large-12 columns">
  <div class="small-8 columns inline-list">
    <img src="<%= @elevator.elevator.large_elevator %>">
    <div class="large-6 columns">
      <h3 class="elevaderfont">Address:</h3>
      <li> <%= @elevator.address %> </li>
      <li><%= @elevator.city %>, <%= @elevator.state %> <%= @elevator.zipcode %> </li>
    </div>
  </div>
  <div class="small-3 columns author">
    <p>Created by: <%= @user.username %></p>
    <div class="avatar-container large">
      <img src="<%= @user.avatar.small_avatar %>">
    </div>
  </div>
</div>

<div class="row">
  <% if current_user %>
    <%= form_for [@elevator, @review] do |f| %>
      <div class="small-2 medium-4 large-6">
        <%= f.label :rating %>
        <%= f.select :rating, options_for_select(@rating) %>
      </div>
        <%= f.label :body %>
        <%= f.text_area :body %>
        <%= f.submit "Create Review", class: "button tiny secondary button-span round" %>
    <% end %>
  <% end %>
</div>

<div class="row reviews">
  <% @reviews.each do |review| %>
    <div class="review row" id="review-<%= review.id %>">
      <div class="user-info small-2 columns">
        <div class="small-block-grid-6 avatar-container small">
          <img src="<%= review.user.avatar %>">
        </div>
        <div class="small-block-grid-4" id="username">
          <p> <%= review.user.username %> </p>
        </div>
      </div>
      <div class="rating small-6 columns">
        <div class="stars">
          <p class="hidden-rating">Rating: <%= review.rating %></p>
          <%= render 'elevators/stars', locals: { gold: review.rating, silver: 5 - review.rating } %>
        </div>
        <div class="review-body"><p> <%= review.body %> </p></div>
      </div>
      <div class="small-2 columns">
        <div class="voting">
          <div class="upvote small-4 columns">
            <%= form_tag review_votes_path(review), method: :post do  %>
            <%= hidden_field_tag :vote, "1" %>
            <%= submit_tag 'Up', class: 'vote', id: "upvote", type: :image, :src => image_path("up.png") %>
            <% end %>
          </div>
          <div class="vote-total small-4 columns" id="vote-total-<%= review.id %>">
            <%= review.total_votes %>
          </div>
          <div class="downvote small-4 columns">
            <%= form_tag review_votes_path(review), method: :post do  %>
            <%= hidden_field_tag :vote, "-1" %>
            <%= submit_tag 'Down', class: 'vote', id: "downvote", type: :image, :src => image_path("down.png")%>
            <% end %>
          </div>
        </div>
        <ul class="review-edits button-group even-2 round">
          <% if current_user == review.user %>
            <li><%= link_to "Edit Review", edit_review_path(review), class: "button tiny" %></li>
          <% end %>
          <% if current_user == review.user || current_admin %>
            <li><%= link_to "Delete Review", review, method: :delete, class: "button tiny alert" %></li>
          <% end %>
        </div>
      </ul>
  </div>
  <% end %>
</div>

<div id ="paginator">
  <%= paginate @reviews %>
</div>