config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root to: 'homes#index'
  resources :users

  authenticate :user do
    resources :elevators, only: [:new, :create, :update, :edit] do
      resources :reviews, only: [:create]
    end
    resources :reviews, only: [:edit, :update] do
      resources :votes, only: [:create]
    end
  end

  resources :elevators, only: [:index, :show, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :reviews, only: [:destroy]

  authenticated :admin do
    resources :admins, only: [:index, :create, :destroy]
    resources :users, only: [:index, :update, :destroy]
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="flash <%= type %>">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="elevator-wrapper">
    <div class="btn-cmon">
      <div class="btn btn-up"></div>
      <div class="btn btn-down"></div>
    </div>
    <div class="floor">5</div>
    <div class="floor-name">elevader</div>
    <div class="elevator">
      <div class="door"></div>
      <div class="inside">
        <div class="handrails"></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="contain-to-grid large-12, medium-6, small-2">
  <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: small">
    <ul class="title-area small-3">
      <li class="name">
        <h1><%= link_to "ELEVADER", elevators_path %></h1>
          <img src="/assets/elevader.png" />
      </li>
    </ul>

    <div class="search top-bar-section small-2">
      <ul >
        <%= form_tag search_elevators_path, method: :get do %>
          <li class="searchelement"><%= text_field_tag :search, params[:search], class: "searchbox" %></li>
          <li class="searchelement"><%= submit_tag "Search", class: "button searchbutton", id: "searchbutton" %></li>
        <% end %>
      </ul>
    </div>

    <div class="top-bar-section small-8" id="nav-buttons">
      <ul class="right button-group">
        <% if current_admin %>
            <li><%= link_to "Admins", admins_path %></li>
            <li><%= link_to "Users", users_path %></li>
        <% end %>
        <% if current_user %>
          <li class="avatar-container small" id="nav-avatar">
            <img src="<%= current_user.avatar.small_avatar %>">
          </li>
        <% end %>
        <% if current_user || current_admin %>
          <li><%= link_to "Profile", edit_user_registration_path, id: 'nav-button' %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href='https://fonts.googleapis.com/css?family=Play' rel='stylesheet' type='text/css'>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="../assets/stylesheets/foundation-icons/foundation-icons.css" />

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Elevader</title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body id='body'>
    <div class='container'>
      <header>
        <%= render "layouts/navbar" %>
        <%= render "layouts/flash" %>
      </header>

      <div class="row">
        <%= yield %>
      </div>

      <%= render "layouts/footer" %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>